### ISSUE TITLE
pip install 错误 UnicodeDecodeError: 'charmap' codec can't decode byte

### ISSUE THREAD

**Issue by arisliang** [1dot75cm/xueqiu#1]
我的环境是windows 7, anaconda python 3.7

使用`pip install xueqiu`安装时，有如下错误:

(test) C:\Users\user>pip install xueqiu
Collecting xueqiu
  Downloading https://files.pythonhosted.org/packages/4b/2e/00b8c329e95dd45dcb09
69ff62c93e84809034910f0c61da80cabd457808/xueqiu-0.1.3.1.tar.gz (75kB)
    100% |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 81kB 1.1MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-_fv1y09j\xueqiu\setup.py"
, line 59, in <module>
        long_description=open('README.md').read(),
      File "C:\Users\user\Anaconda3\envs\test\lib\encodings\cp1252.py", line 23, i
n decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 465:
character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppDa
ta\Local\Temp\pip-install-_fv1y09j\xueqiu\

**Comment by 1dot75cm** [comment]
等我白天找个 Windows 试试 @arisliang

**Comment by 1dot75cm** [comment]
@arisliang 感谢，已修复，是编码问题，等我发个新版本

**Comment by 1dot75cm** [comment]
@arisliang 已更，安装参考 https://github.com/1dot75cm/xueqiu#installation
