### ISSUE TITLE
百度指数爬去问题

### ISSUE THREAD

**Issue by yxleung** [1dot75cm/xueqiu#2]
你好，我发现这个项目有代码：baidu_search_live = "http://index.baidu.com/api/LiveApi/getLive?region=&word="；最近我也有需求爬去这个api的数据，我发现这个api返回的数据加密了，请教你一下，有解决方案吗？

**Comment by 1dot75cm** [comment]
代码里有， 看懂 [decrypt](https://github.com/1dot75cm/xueqiu/blob/master/xueqiu/baidu.py#L200) 方法就能解决你的问题 @yxleung

**Comment by 1dot75cm** [comment]
```python
>>> idx = xueqiu.BaiduIndex()
>>> idx.live('股票,基金', '上海')
# return DataFrame
```
已解决 @yxleung
